### PR TITLE
Created package 3.4.1

### PR DESCRIPTION
**Pull request by mudilajaganios**

### CODE REVIEW

**Comment by peterz** [comment]
Why is this not merged?

**Comment by saghul** [comment]
Why should it be?

**Comment by duong-xendit** [comment]
@saghul SPM is the modern for Swift, it is really helpful if it can support SPM

**Comment by saghul** [comment]
It's on our roadmap to support it, but we need to publish WebRTC as SPM first. This is a good start though!

**Comment by valentinwallet** [comment]
@saghul  What is the status of the SPM support ? It seems that you published the WebRTC as SPM already.

**Comment by saghul** [comment]
YEs, we did, I completely forgot about this issue though 😅 

What would be missing here?

**Comment by valentinwallet** [comment]
It seems that the main obstacle to integrating the JitsiMeetSDK with SPM has been overcome by enabling WebRTC with SPM, which has been successfully implemented. Now, the focus is on ensuring compatibility of the JitsiMeetSDK with SPM.

I've also seen an other pull request related to this issue : https://github.com/jitsi/jitsi-meet-ios-sdk-releases/pull/9. Though they may be dated, they can serve as a starting point.

Thank a lot for your message, SPM compatibility would greatly benefit us, offering an alternative to Cocoapods 😊

**Comment by saghul** [comment]
Oh, I had missed #9 too 🤦 

Looks like that one is closer to what's needed, so I'll try to take a look at it soon!

**Comment by valentinwallet** [comment]
Hey @saghul any news on this? Let me know if I can help you 😃

**Comment by saghul** [comment]
Looks like we are close. I am not very familiar with the syntax. These dependencies need to be put there too: https://github.com/jitsi/jitsi-meet-ios-sdk-releases/blob/6541d094c60b4d58246199cf6cfea7272cecda8e/JitsiMeetSDK.podspec#L13

**Comment by saghul** [comment]
At this point it would be helpful to have a new PR with all changes applied. We just released SDK 9.2.2 so it will take a few weeks until we do the next. It should be attainable to merge before the next one. Are you up for that?

**Comment by valentinwallet** [comment]
Yes I can try that !

**Comment by valentinwallet** [comment]
Hey @saghul you can have a look at it here : https://github.com/jitsi/jitsi-meet-ios-sdk-releases/pull/11 😃

**Comment by saghul** [comment]
Continues in https://github.com/jitsi/jitsi-meet-ios-sdk-releases/pull/11

**Pull request closed without merging**
